### ISSUE TITLE
I don't understand how to setup my DevEnv

### ISSUE THREAD

**Issue by ghost** [UnseenWizzard/git_training#113]
Hello.
I'm working through your tutorial as part of the pre-work for a BootCamp.

I'm trying to setup my DevEnv, and I don't understand how to link those three folders to Git.

Do I create them on my HD and tell git where they are at?
Is the Git folder in my user account my WorkingDir?
Is the Desktop app my local repository?

I keep trying to create these in my Documents, but my clones show up in the Git folder in my user account, while Terminal is sending them to a folder I created.

I tried to fix the problem myself by deleting and moving things, and that just made it worse.

I'm fine uninstalling and restarting, but that doesn't fix the problem in Terminal.

I'm just looking for a clean start with everything in the right place for me to begin. I don't have anything I can't afford to lose.

**Comment by ghost** [comment]
When I clone, how does it get to the LocalRepo and the WrkDir?

**Comment by UnseenWizzard** [comment]
Hi. This tutorial generally assumes you have git installed and used in a command line. 

I'm not sure what desktop app or graphical UI you're using, and I think who ever included my tutorial in your bootcamp is better suited to help you with that. 
It sounds like whatever setup that is doing on top of git is messing things up for you here. 

In general if you do a `git clone` of a/this repo either in your Linux terminal or the git-bash terminal you get when installing from git-scm for Windows(*), that folder you've cloned will be your local working dir and contain the local repo data in the .git folder in there. 
You shouldn't need any more setup than that. 

(*) I don't know about Mac

**Comment by ghost** [comment]
Thank you

**Comment by UnseenWizzard** [comment]
Sure thing 👍 

Hope it helped a bit. All the best with your bootcamp.
