### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by joapuiib** [UnseenWizzard/git_training#145]
Hello,
I'm creating some slides for my students about Git and I would love to use the images provided in this repository. I can't find any information about the license of the contents of this repository.

First, have you thought of adding any kind of license?

Can I use the images? If so, how should I reference it and give appropriate credit?

Thanks in advance.

**Comment by UnseenWizzard** [comment]
Hi @joapuiib , sorry for my late reply and thanks for being mindful of license and attribution! 

I've created this as an educational resource and thus 100%  approve and encourage using it with your students. 

I'll look into adding a fitting Creative Commons license for this. 
For now, if you haven't already absolutely use it, and kindly just mention and link to the repo for attribution.

**Comment by joapuiib** [comment]
Thanks for letting us use this resource.

I'll leave the issue open as a reminder that there isn't a license.

**Comment by UnseenWizzard** [comment]
This is now [CC BY-SA](https://creativecommons.org/licenses/by-sa/4.0/) licensed.
